USE [PH2];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE [EPROVEEDOR].[SP_COMPRA_SECTOR]
    @ACCION        VARCHAR(100),
    @ID_SECTOR     INT           = NULL,
    @ID_TIPO_OPERA INT           = NULL,   -- NUEVO: para cascada
    @ID_CLASIFICA  INT           = NULL,   -- NUEVO: para cascada
    @CODIGO        VARCHAR(5)    = NULL,
    @NOMBRE        NVARCHAR(100) = NULL,
    @FILTRO        NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF @ACCION = 'BUSCAR'
    BEGIN
        SELECT TOP 20 ID_SECTOR, CODIGO, NOMBRE
        FROM COMPRA_SECTOR
        WHERE (@FILTRO IS NULL
               OR NOMBRE LIKE '%' + @FILTRO + '%'
               OR CODIGO LIKE '%' + @FILTRO + '%')
        ORDER BY NOMBRE
    END

    ELSE IF @ACCION = 'COMBO'
    BEGIN
        -- Solo los sectores permitidos para el TIPO_OPERA + CLASIFICA seleccionados
        SELECT DISTINCT S.ID_SECTOR, S.CODIGO, CODIGO + ' - ' + NOMBRE AS NOMBRE
        FROM COMPRA_SECTOR S
        INNER JOIN COMPRA_TPCOSTGAST M ON M.ID_SECTOR = S.ID_SECTOR
        WHERE M.ID_TIPO_OPERA = @ID_TIPO_OPERA
          AND M.ID_CLASIFICA  = @ID_CLASIFICA
        ORDER BY S.ID_SECTOR
    END

    ELSE IF @ACCION = 'OBTENER'
    BEGIN
        SELECT ID_SECTOR, CODIGO, NOMBRE
        FROM COMPRA_SECTOR
        WHERE ID_SECTOR = @ID_SECTOR
    END

    ELSE IF @ACCION = 'GUARDAR'
    BEGIN
        DECLARE @NUEVO_ID_CS INT
        IF @ID_SECTOR = 0
        BEGIN
            SELECT @NUEVO_ID_CS = ISNULL(MAX(ID_SECTOR), 0) + 1 FROM COMPRA_SECTOR
            INSERT INTO COMPRA_SECTOR (ID_SECTOR, CODIGO, NOMBRE)
            VALUES (@NUEVO_ID_CS, @CODIGO, @NOMBRE)
            SELECT @NUEVO_ID_CS AS ID_GENERADO
        END
        ELSE
        BEGIN
            UPDATE COMPRA_SECTOR
            SET CODIGO = @CODIGO, NOMBRE = @NOMBRE
            WHERE ID_SECTOR = @ID_SECTOR
            SELECT @ID_SECTOR AS ID_GENERADO
        END
    END

    ELSE IF @ACCION = 'ELIMINAR'
        DELETE FROM COMPRA_SECTOR WHERE ID_SECTOR = @ID_SECTOR
END
GO
