USE [PH2];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE [EPROVEEDOR].[SP_COMPRA_TIPO_OPERACION]
    @ACCION        VARCHAR(100),
    @ID_TIPO_OPERA INT           = NULL,
    @CODIGO        VARCHAR(5)    = NULL,
    @NOMBRE        NVARCHAR(100) = NULL,
    @FILTRO        NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF @ACCION = 'BUSCAR'
    BEGIN
        SELECT TOP 20 ID_TIPO_OPERA, CODIGO, NOMBRE
        FROM COMPRA_TIPO_OPERACION
        WHERE (@FILTRO IS NULL
               OR NOMBRE LIKE '%' + @FILTRO + '%'
               OR CODIGO LIKE '%' + @FILTRO + '%')
        ORDER BY NOMBRE
    END

    ELSE IF @ACCION = 'COMBO'
    BEGIN
        SELECT ID_TIPO_OPERA, CODIGO, CODIGO + ' - ' + NOMBRE AS NOMBRE
        FROM COMPRA_TIPO_OPERACION
        ORDER BY CODIGO
    END

    ELSE IF @ACCION = 'OBTENER'
    BEGIN
        SELECT ID_TIPO_OPERA, CODIGO, NOMBRE
        FROM COMPRA_TIPO_OPERACION
        WHERE ID_TIPO_OPERA = @ID_TIPO_OPERA
    END

    ELSE IF @ACCION = 'GUARDAR'
    BEGIN
        DECLARE @NUEVO_ID_CTO INT
        IF @ID_TIPO_OPERA = 0
        BEGIN
            SELECT @NUEVO_ID_CTO = ISNULL(MAX(ID_TIPO_OPERA), 0) + 1 FROM COMPRA_TIPO_OPERACION
            INSERT INTO COMPRA_TIPO_OPERACION (ID_TIPO_OPERA, CODIGO, NOMBRE)
            VALUES (@NUEVO_ID_CTO, @CODIGO, @NOMBRE)
            SELECT @NUEVO_ID_CTO AS ID_GENERADO
        END
        ELSE
        BEGIN
            UPDATE COMPRA_TIPO_OPERACION
            SET CODIGO = @CODIGO, NOMBRE = @NOMBRE
            WHERE ID_TIPO_OPERA = @ID_TIPO_OPERA
            SELECT @ID_TIPO_OPERA AS ID_GENERADO
        END
    END

    ELSE IF @ACCION = 'ELIMINAR'
        DELETE FROM COMPRA_TIPO_OPERACION WHERE ID_TIPO_OPERA = @ID_TIPO_OPERA
END
GO
