USE [PH2];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

--EXEC SP_QUEDAN_RPT 'LISTADO_COMPROBANTES_RECIBIDOS', '01/01/2026', '30/06/2026'

CREATE OR ALTER PROCEDURE [EPROVEEDOR].[SP_QUEDAN_RPT]
@ACCION		VARCHAR(100) = NULL,
@ID_QUEDAN	INT=NULL,
@FECHA_INI	DATETIME = NULL,
@FECHA_FIN	DATETIME = NULL,
@CLASIFICAR_POR_ORDEN_COMPRA BIT = NULL,
@GRUPO		INT = NULL /*	1) JIBOA    2) PLANTA COGENERACION	3) PLANTA FOTOVOLTAICA */

AS
BEGIN
	IF @ACCION = 'LISTADO_COMPROBANTES_RECIBIDOS'
		BEGIN
		SELECT 
			X.*
		FROM (
			SELECT 
				Q.NUM_QUEDAN, 
				T.ABREVIATURA AS TIPO_DTE,
				C.COD_GENERACION, 
				C.FECHA_EMISION,
				C.FECHA_RECIBIDO,
				C.FECHA_VENCE,
				E.NOMBRE,
				C.ORDEN,
				C.GRAVADA + C.EXENTA AS AFECTA,
				C.SALDO AS TOTAL,
				CASE WHEN ID_CHEQUE > 0 THEN 0 ELSE C.SALDO END AS SALDO,
				(SELECT RT.COD_GENERACION FROM COMPROBANTE_RETENCION RT WHERE RT.ID_COMPROBANTE_RET = C.ID_COMPROBANTE_RET) AS NUMRET,
				CASE 
					WHEN ISNULL(@CLASIFICAR_POR_ORDEN_COMPRA,0) = 0 THEN 1					
					ELSE
						CASE 				
							WHEN ISNULL(ORDEN,'*') = '*'				THEN 1	-- JIBOA
							WHEN SUBSTRING(ISNULL(ORDEN,'*'),1,1) = 'A' THEN 2	-- PLANTA COGENERACION
							WHEN SUBSTRING(ISNULL(ORDEN,'*'),1,1) = 'F' THEN 3	-- PLANTA FOTOVOLTAICA
							ELSE 1
						END 
				END AS GRUPO
			FROM QUEDAN Q, [EPROVEEDOR].[COMPRA_EXTERIOR] C, TIPO_DTE T, ENTIDAD E
			WHERE Q.ID_QUEDAN = C.ID_QUEDAN
				AND C.ID_TIPO_DTE = T.ID_TIPO_DTE
				AND C.ID_ENTIDAD = E.ID_ENTIDAD
				AND C.FECHA_RECIBIDO BETWEEN @FECHA_INI AND @FECHA_FIN
				AND C.ID_TIPO_DTE IN(2,21)			
		) X
		WHERE (@GRUPO IS NULL OR @GRUPO = GRUPO)
		ORDER BY GRUPO, NUM_QUEDAN ASC
		END	
	ELSE IF @ACCION = 'QUEDAN'
		BEGIN
		SELECT 
			C.ID_COMPRA_EXTERIOR AS ID_CCF_COMPRA,
			(SELECT E.NOMBRE FROM ENTIDAD E WHERE E.ID_ENTIDAD = Q.ID_ENTIDAD) AS NOM_PROVEEDOR,
			(SELECT T.ABREVIATURA FROM TIPO_DTE T WHERE T.ID_TIPO_DTE = C.ID_TIPO_DTE) AS COMPROB,
			C.COD_GENERACION AS NUMERO,
			C.ORDEN AS ORDEN_COMPRA,
			C.SALDO AS VALOR,
			C.OBSERVACION AS SOLICITADO_POR,
			C.FECHA_RECIBIDO AS FECHA,
			LOWER(FORMAT(C.FECHA_RECIBIDO, 'dd \D\E MMMM \D\E yyyy', 'es-SV')) AS FECHA_LETRAS,
			(SELECT T.NOMBRE FROM USUARIO T WHERE T.USUARIO = C.USUARIO_CREA) AS ENTREGADO_POR,
			Q.NUM_QUEDAN AS QUEDAN,
			(SELECT T.COD_GENERACION FROM COMPROBANTE_RETENCION T WHERE T.ID_COMPROBANTE_RET = C.ID_COMPROBANTE_RET) AS NUMRETE,
			(SELECT T.NUM_CONTROL FROM COMPROBANTE_RETENCION T WHERE T.ID_COMPROBANTE_RET = C.ID_COMPROBANTE_RET) AS NUMCONTROL,
			(SELECT T.SELLO_RECIBIDO FROM COMPROBANTE_RETENCION T WHERE T.ID_COMPROBANTE_RET = C.ID_COMPROBANTE_RET) AS SELLORECEPCION
		FROM QUEDAN Q, [EPROVEEDOR].[COMPRA_EXTERIOR] C
		WHERE Q.ID_QUEDAN = C.ID_QUEDAN
		AND Q.ID_QUEDAN = @ID_QUEDAN
		ORDER BY Q.ID_QUEDAN, C.ID_COMPRA_EXTERIOR ASC
		END
END
GO
