USE [PH2];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE [EPROVEEDOR].[SP_COMPROBANTE_RETENCION_RPT]
@ACCION NVARCHAR(100),
@ID_CCF_COMPRA INT
AS
BEGIN
	IF @ACCION = 'COMPROBANTE_RETENCION'
		BEGIN
			SELECT 
				R.ID_COMPROBANTE_RET,
				R.COD_GENERACION,
				R.NUM_CONTROL,
				R.SELLO_RECIBIDO,
				REVERSE(LEFT(REVERSE(R.NUM_CONTROL), CHARINDEX('-', REVERSE(R.NUM_CONTROL)) - 1)) AS NUM_INTERNO,
				(SELECT T.NOMBRE FROM MODELO_FACTURACION T WHERE T.ID_MODELO_FACT = R.ID_MODELO_FACT) MODELO_FACT,
				R.VERSION,
				(SELECT T.VALORES FROM AMBIENTE_DESTINO T WHERE T.CODIGO = R.AMBIENTE) AMBIENTE,
				(SELECT T.NOMBRE FROM TIPO_OPERACION T WHERE T.ID_TIPO_OPERACION = R.ID_TIPO_OPERACION) TIPO_TRANSMISION,
				CONVERT(VARCHAR(10), F.FECHA_EMISION, 103) + ' ' + R.HORA_EMISION AS FH_EMISION,
				R.FHPROCESAMIENTO,	
				E.NOMBRE,
				E.NIT,
				E.NRC,
				IIF(ISNULL(E.TELEFONO,'')='',E.CELULAR,E.TELEFONO) AS TELEFONO,
				R.TIPO_MONEDA,
				IIF(E.COMPLEMENTO = '', ISNULL(E.COLONIA,'') + ' ' + ISNULL(CALLE,'') + ' ' + IIF(ISNULL(E.CASA,'')='','','#' + E.CASA), E.COMPLEMENTO) AS DIRECCION,
				CASE 
					WHEN R.SELLO_RECIBIDO <> '' THEN
						'https://admin.factura.gob.sv/consultaPublica?ambiente=01&codGen=' 
							+ R.COD_GENERACION + '&fechaEmi=' 
							+  CONVERT(VARCHAR(10), R.FECHA_CREA, 23) 
					ELSE 'SIN SELLO'
				END AS URL_VALIDACION,
				(SELECT T.NOMBRE FROM TIPO_CONTRIBUYENTE T WHERE T.ID_TIPO_CONTRIB = E.ID_TIPO_CONTRIB) AS TIPO_CONTRIBUYENTE,
				(SELECT T.CODI_MH + ' - ' + T.VALORES FROM ACTIVIDAD_ECONOMICA T WHERE T.ID_ACTIVIDAD = E.ID_ACTIVIDAD_1) AS ACTIVIDAD,
				E.CORREO,
				(SELECT T.NOMBRE_DISTRITO FROM MUNICIPIO T WHERE T.CODI_DEPTO = E.CODI_DEPTO AND T.CODI_MUNI = E.CODI_MUNI) AS MUNICIPIO,
				(SELECT T.VALORES FROM DEPARTAMENTO T WHERE T.CODI_DEPTO = E.CODI_DEPTO) AS DEPARTAMENTO,
				R.CUERPO_DESCRIPCION AS DETALLE,
				R.RESU_TOTAL_IVA_RET_L,
				R.RESU_TOTAL_SUJETO_RET,
				R.RESU_TOTAL_IVA_RET,
				R.RESU_TOTAL_SUJETO_RET - R.RESU_TOTAL_IVA_RET AS TOTAL,
				IIF(R.ANULADO = 1, 'DOCUMENTO ANULADO', '') AS ANULADO -- OJO: PENDIENTE DE DONDE SE TOMARAN LOS DATOS DEL EVENTO DE INVALIDACION
			FROM COMPROBANTE_RETENCION R, [EPROVEEDOR].[COMPRA_EXTERIOR] F, ENTIDAD E
			WHERE R.ID_COMPROBANTE_RET = F.ID_COMPROBANTE_RET
			AND F.ID_ENTIDAD = E.ID_ENTIDAD
			AND F.ID_COMPRA_EXTERIOR = @ID_CCF_COMPRA
		END
END
GO
