USE [PH2];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE [EPROVEEDOR].[SP_COMPRA_TIPO_SERVICIO]
    @ACCION        VARCHAR(100),
    @ID_TIPO_SERVI INT           = NULL,
    @CODIGO        VARCHAR(5)    = NULL,
    @NOMBRE        NVARCHAR(100) = NULL,
    @FILTRO        NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF @ACCION = 'BUSCAR'
    BEGIN
        SELECT TOP 20 ID_TIPO_SERVI, CODIGO, NOMBRE, ID_TIPO_RENTA
        FROM COMPRA_TIPO_SERVICIO
        WHERE (@FILTRO IS NULL
               OR NOMBRE LIKE '%' + @FILTRO + '%'
               OR CODIGO LIKE '%' + @FILTRO + '%')
        ORDER BY ID_TIPO_SERVI
    END

    ELSE IF @ACCION = 'COMBO'
    BEGIN
        SELECT ID_TIPO_SERVI, CODIGO, CODIGO + ' - ' + NOMBRE AS NOMBRE, ID_TIPO_RENTA
        FROM COMPRA_TIPO_SERVICIO
        ORDER BY ID_TIPO_SERVI
    END

    ELSE IF @ACCION = 'OBTENER'
    BEGIN
        SELECT ID_TIPO_SERVI, CODIGO, NOMBRE, ID_TIPO_RENTA
        FROM COMPRA_TIPO_SERVICIO
        WHERE ID_TIPO_SERVI = @ID_TIPO_SERVI
    END

    ELSE IF @ACCION = 'GUARDAR'
    BEGIN
        DECLARE @NUEVO_ID_CTS INT
        IF @ID_TIPO_SERVI = 0
        BEGIN
            SELECT @NUEVO_ID_CTS = ISNULL(MAX(ID_TIPO_SERVI), 0) + 1 FROM COMPRA_TIPO_SERVICIO
            INSERT INTO COMPRA_TIPO_SERVICIO (ID_TIPO_SERVI, CODIGO, NOMBRE)
            VALUES (@NUEVO_ID_CTS, @CODIGO, @NOMBRE)
            SELECT @NUEVO_ID_CTS AS ID_GENERADO
        END
        ELSE
        BEGIN
            UPDATE COMPRA_TIPO_SERVICIO
            SET CODIGO = @CODIGO, NOMBRE = @NOMBRE
            WHERE ID_TIPO_SERVI = @ID_TIPO_SERVI
            SELECT @ID_TIPO_SERVI AS ID_GENERADO
        END
    END

    ELSE IF @ACCION = 'ELIMINAR'
        DELETE FROM COMPRA_TIPO_SERVICIO WHERE ID_TIPO_SERVI = @ID_TIPO_SERVI
END
GO
