USE [PH2];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

-- ----------------------------------------------------------------
-- SP: SUCURSAL
-- ----------------------------------------------------------------
CREATE OR ALTER PROCEDURE [EPROVEEDOR].[SP_SUCURSAL]
    @ACCION      VARCHAR(50),
    @ID_SUCURSAL INT           = NULL,
    @NOMBRE      NVARCHAR(100) = NULL,
    @FILTRO      NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF @ACCION = 'BUSCAR'
    BEGIN
        SELECT TOP 20 ID_SUCURSAL, NOMBRE
        FROM SUCURSAL
        WHERE (@FILTRO IS NULL OR NOMBRE LIKE '%' + @FILTRO + '%')
        ORDER BY NOMBRE
    END

    ELSE IF @ACCION = 'OBTENER_SUCURSAL' -- * ROBERTO * --
    BEGIN
    SELECT 
       [TIPOESTABLECIMIENTO] AS SUCURSAL 
      ,[NOMBRE] AS NOMBRE
      ,[CODSUCURSAL] AS CORRELATIVO
    FROM SUCURSAL
    END

    ELSE IF @ACCION = 'OBTENER'
    BEGIN
        SELECT ID_SUCURSAL, NOMBRE FROM SUCURSAL WHERE ID_SUCURSAL = @ID_SUCURSAL
    END

    ELSE IF @ACCION = 'GUARDAR'
    BEGIN
        DECLARE @NUEVO_ID_S INT
        IF @ID_SUCURSAL = 0
        BEGIN
            SELECT @NUEVO_ID_S = ISNULL(MAX(ID_SUCURSAL), 0) + 1 FROM SUCURSAL
            INSERT INTO SUCURSAL (ID_SUCURSAL, NOMBRE) VALUES (@NUEVO_ID_S, @NOMBRE)
            SELECT @NUEVO_ID_S AS ID_GENERADO
        END
        ELSE
        BEGIN
            UPDATE SUCURSAL SET NOMBRE = @NOMBRE WHERE ID_SUCURSAL = @ID_SUCURSAL
            SELECT @ID_SUCURSAL AS ID_GENERADO
        END
    END

    ELSE IF @ACCION = 'ELIMINAR'
    BEGIN
        DELETE FROM SUCURSAL WHERE ID_SUCURSAL = @ID_SUCURSAL
    END
END
GO
