USE [PH2];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE [EPROVEEDOR].[SP_COMPRA_TIPO_COSTO]
    @ACCION        VARCHAR(100),
    @ID_TIPO_COSTO INT           = NULL,
    @ID_TIPO_OPERA INT           = NULL,   -- NUEVO: para cascada
    @ID_CLASIFICA  INT           = NULL,   -- NUEVO: para cascada
    @ID_SECTOR     INT           = NULL,   -- NUEVO: para cascada
    @CODIGO        VARCHAR(5)    = NULL,
    @NOMBRE        NVARCHAR(100) = NULL,
    @FILTRO        NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF @ACCION = 'BUSCAR'
    BEGIN
        SELECT TOP 20 ID_TIPO_COSTO, CODIGO, NOMBRE
        FROM COMPRA_TIPO_COSTO
        WHERE (@FILTRO IS NULL
               OR NOMBRE LIKE '%' + @FILTRO + '%'
               OR CODIGO LIKE '%' + @FILTRO + '%')
        ORDER BY NOMBRE
    END

    ELSE IF @ACCION = 'COMBO'
    BEGIN
        -- Solo los tipos de costo permitidos para la combinación seleccionada
        SELECT DISTINCT T.ID_TIPO_COSTO, T.CODIGO, CODIGO + ' - ' + NOMBRE AS NOMBRE
        FROM COMPRA_TIPO_COSTO T
        INNER JOIN COMPRA_TPCOSTGAST M ON M.ID_TIPO_COSTO = T.ID_TIPO_COSTO
        WHERE M.ID_TIPO_OPERA = @ID_TIPO_OPERA
          AND M.ID_CLASIFICA  = @ID_CLASIFICA
          AND M.ID_SECTOR     = @ID_SECTOR
        ORDER BY T.ID_TIPO_COSTO
    END

    ELSE IF @ACCION = 'OBTENER'
    BEGIN
        SELECT ID_TIPO_COSTO, CODIGO, NOMBRE
        FROM COMPRA_TIPO_COSTO
        WHERE ID_TIPO_COSTO = @ID_TIPO_COSTO
    END

    ELSE IF @ACCION = 'GUARDAR'
    BEGIN
        DECLARE @NUEVO_ID_CTC INT
        IF @ID_TIPO_COSTO = 0
        BEGIN
            SELECT @NUEVO_ID_CTC = ISNULL(MAX(ID_TIPO_COSTO), 0) + 1 FROM COMPRA_TIPO_COSTO
            INSERT INTO COMPRA_TIPO_COSTO (ID_TIPO_COSTO, CODIGO, NOMBRE)
            VALUES (@NUEVO_ID_CTC, @CODIGO, @NOMBRE)
            SELECT @NUEVO_ID_CTC AS ID_GENERADO
        END
        ELSE
        BEGIN
            UPDATE COMPRA_TIPO_COSTO
            SET CODIGO = @CODIGO, NOMBRE = @NOMBRE
            WHERE ID_TIPO_COSTO = @ID_TIPO_COSTO
            SELECT @ID_TIPO_COSTO AS ID_GENERADO
        END
    END

    ELSE IF @ACCION = 'ELIMINAR'
        DELETE FROM COMPRA_TIPO_COSTO WHERE ID_TIPO_COSTO = @ID_TIPO_COSTO
END
GO
