USE [PH2];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE [EPROVEEDOR].[SP_COMPRA_CLASIFICACION]
    @ACCION        VARCHAR(100),
    @ID_CLASIFICA  INT           = NULL,
    @ID_TIPO_OPERA INT           = NULL,   -- NUEVO: para cascada
    @CODIGO        VARCHAR(5)    = NULL,
    @NOMBRE        NVARCHAR(100) = NULL,
    @FILTRO        NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF @ACCION = 'BUSCAR'
    BEGIN
        SELECT TOP 20 ID_CLASIFICA, CODIGO, NOMBRE
        FROM COMPRA_CLASIFICACION
        WHERE (@FILTRO IS NULL
               OR NOMBRE LIKE '%' + @FILTRO + '%'
               OR CODIGO LIKE '%' + @FILTRO + '%')
        ORDER BY NOMBRE
    END

    ELSE IF @ACCION = 'COMBO'
    BEGIN
        -- Solo las clasificaciones permitidas para el TIPO_OPERA seleccionado
        SELECT DISTINCT C.ID_CLASIFICA, C.CODIGO, C.CODIGO + ' - ' + C.NOMBRE AS NOMBRE
        FROM COMPRA_CLASIFICACION C
        INNER JOIN COMPRA_TPCOSTGAST M ON M.ID_CLASIFICA = C.ID_CLASIFICA
        WHERE M.ID_TIPO_OPERA = @ID_TIPO_OPERA
        ORDER BY  C.ID_CLASIFICA
    END

    ELSE IF @ACCION = 'OBTENER'
    BEGIN
        SELECT ID_CLASIFICA, CODIGO, NOMBRE
        FROM COMPRA_CLASIFICACION
        WHERE ID_CLASIFICA = @ID_CLASIFICA
    END

    ELSE IF @ACCION = 'GUARDAR'
    BEGIN
        DECLARE @NUEVO_ID_CC INT
        IF @ID_CLASIFICA = 0
        BEGIN
            SELECT @NUEVO_ID_CC = ISNULL(MAX(ID_CLASIFICA), 0) + 1 FROM COMPRA_CLASIFICACION
            INSERT INTO COMPRA_CLASIFICACION (ID_CLASIFICA, CODIGO, NOMBRE)
            VALUES (@NUEVO_ID_CC, @CODIGO, @NOMBRE)
            SELECT @NUEVO_ID_CC AS ID_GENERADO
        END
        ELSE
        BEGIN
            UPDATE COMPRA_CLASIFICACION
            SET CODIGO = @CODIGO, NOMBRE = @NOMBRE
            WHERE ID_CLASIFICA = @ID_CLASIFICA
            SELECT @ID_CLASIFICA AS ID_GENERADO
        END
    END

    ELSE IF @ACCION = 'ELIMINAR'
        DELETE FROM COMPRA_CLASIFICACION WHERE ID_CLASIFICA = @ID_CLASIFICA
END
GO
