USE [PH2]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [ESOLICITUD].[SP_SOLICITUDES_SIGESTA]
    @CODIPROVEEDOR NVARCHAR(20),
    @ID_ZAFRA INT,
    @ACTION NVARCHAR(30) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF @ACTION IS NULL OR @ACTION = N'PRODUCTOR_ENCABEZADO'
    BEGIN
        SELECT DISTINCT
            'PRODUCTOR' AS TIPO_SOLICITUD,
            1 AS ID_TIPO_SOLICITUD,
            ENCA.ID_SOLICITUD,
            ENCA.ID_ZAFRA,
            [INJIBOA].[dbo].[nombrezafra](ENCA.ID_ZAFRA) AS NOMBRE_ZAFRA,
            ENCA.NUM_SOLICITUD,
            ENCA.CODIPROVEEDOR,
            ENCA.NOMBRE_PROVEEDOR,
            ENCA.ID_CUENTA_FINAN,
            CF.NOMBRE_CUENTA,
            ENCA.SUB_TOTAL,
            ENCA.IVA,
            ENCA.TOTAL
        FROM [INJIBOA].[dbo].[SOLIC_AGRICOLA] AS ENCA
        INNER JOIN [INJIBOA].[dbo].[SOLIC_AGRICOLA_PRODUCTO] AS DETA
            ON ENCA.ID_SOLICITUD = DETA.ID_SOLICITUD
        INNER JOIN [INJIBOA].[dbo].[CUENTA_FINAN] AS CF
            ON ENCA.ID_CUENTA_FINAN = CF.ID_CUENTA_FINAN
        WHERE ENCA.ID_ZAFRA = @ID_ZAFRA
          AND ENCA.CODIPROVEEDOR = @CODIPROVEEDOR
          AND DETA.ID_PROVEE = 4
        ORDER BY ENCA.NUM_SOLICITUD DESC;
    END;

    IF @ACTION IS NULL OR @ACTION = N'PRODUCTOR_DETALLE'
    BEGIN
        SELECT
            DETA.ID_SOLIC_AGRI_PROD,
            DETA.ID_SOLICITUD,
            DETA.UID_SOLIC_AGRI_PROD,
            DETA.ID_PRODUCTO,
            DETA.NOMBRE_PRODUCTO,
            DETA.TOTAL_PRODUCTO AS CANTIDAD,
            DETA.PRECIO_UNITARIO,
            DETA.PRECIO_TOTAL AS TOTAL,
            P.COD_REF
        FROM [INJIBOA].[dbo].[SOLIC_AGRICOLA] AS ENCA
        INNER JOIN [INJIBOA].[dbo].[SOLIC_AGRICOLA_PRODUCTO] AS DETA
            ON ENCA.ID_SOLICITUD = DETA.ID_SOLICITUD
        INNER JOIN [INJIBOA].[dbo].[PRODUCTO] AS P
            ON DETA.ID_PRODUCTO = P.ID_PRODUCTO
        WHERE ENCA.ID_ZAFRA = @ID_ZAFRA
          AND ENCA.CODIPROVEEDOR = @CODIPROVEEDOR
          AND DETA.ID_PROVEE = 4
        ORDER BY DETA.ID_SOLICITUD, DETA.NOMBRE_PRODUCTO;
    END;
END
GO
