USE [PH2];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

-- =====================================================================
-- Agrega columnas para conservar el historial de lo importado desde la
-- integración con SIGESTA (solicitud agrícola) al guardar un CCF.
--   - [EDTE].[CREDITOFISCAL_ENC]: NUM_SOLICITUD, NOMBRE_CUENTA,
--     UID_SOLIC_AGRICOLA (referencia a ENCA.UID_SOLIC_AGRICOLA de
--     ACTION='PRODUCTOR_ENCABEZADO' en [ESOLICITUD].[SP_SOLICITUDES_SIGESTA]).
--   - [EDTE].[CREDITOFISCAL_DET]: ID_SOLICITUD, ID_SOLIC_AGRI_PROD,
--     UID_SOLIC_AGRI_PROD (trazabilidad hacia ACTION='PRODUCTOR_DETALLE').
-- Ejecutar ANTES de desplegar EDTE.SP_CREDITOFISCAL_ENC / SP_CREDITOFISCAL_DET
-- actualizados, ya que esos SP ya referencian estas columnas.
-- =====================================================================

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'[EDTE].[CREDITOFISCAL_ENC]', N'U') IS NULL
        THROW 50000, N'No existe la tabla EDTE.CREDITOFISCAL_ENC.', 1;

    IF OBJECT_ID(N'[EDTE].[CREDITOFISCAL_DET]', N'U') IS NULL
        THROW 50001, N'No existe la tabla EDTE.CREDITOFISCAL_DET.', 1;

    -- ---------- EDTE.CREDITOFISCAL_ENC ----------
    IF COL_LENGTH(N'[EDTE].[CREDITOFISCAL_ENC]', N'NUM_SOLICITUD') IS NULL
    BEGIN
        ALTER TABLE [EDTE].[CREDITOFISCAL_ENC]
            ADD [NUM_SOLICITUD] NVARCHAR(20) NULL;
    END;

    IF COL_LENGTH(N'[EDTE].[CREDITOFISCAL_ENC]', N'NOMBRE_CUENTA') IS NULL
    BEGIN
        ALTER TABLE [EDTE].[CREDITOFISCAL_ENC]
            ADD [NOMBRE_CUENTA] NVARCHAR(200) NULL;
    END;

    IF COL_LENGTH(N'[EDTE].[CREDITOFISCAL_ENC]', N'UID_SOLIC_AGRICOLA') IS NULL
    BEGIN
        ALTER TABLE [EDTE].[CREDITOFISCAL_ENC]
            ADD [UID_SOLIC_AGRICOLA] NVARCHAR(40) NULL;
    END;

    -- ---------- EDTE.CREDITOFISCAL_DET ----------
    IF COL_LENGTH(N'[EDTE].[CREDITOFISCAL_DET]', N'ID_SOLICITUD') IS NULL
    BEGIN
        ALTER TABLE [EDTE].[CREDITOFISCAL_DET]
            ADD [ID_SOLICITUD] INT NULL;
    END;

    IF COL_LENGTH(N'[EDTE].[CREDITOFISCAL_DET]', N'ID_SOLIC_AGRI_PROD') IS NULL
    BEGIN
        ALTER TABLE [EDTE].[CREDITOFISCAL_DET]
            ADD [ID_SOLIC_AGRI_PROD] INT NULL;
    END;

    IF COL_LENGTH(N'[EDTE].[CREDITOFISCAL_DET]', N'UID_SOLIC_AGRI_PROD') IS NULL
    BEGIN
        ALTER TABLE [EDTE].[CREDITOFISCAL_DET]
            ADD [UID_SOLIC_AGRI_PROD] NVARCHAR(40) NULL;
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO

SELECT
    TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE (TABLE_SCHEMA = N'EDTE' AND TABLE_NAME = N'CREDITOFISCAL_ENC'
       AND COLUMN_NAME IN (N'NUM_SOLICITUD', N'NOMBRE_CUENTA', N'UID_SOLIC_AGRICOLA'))
   OR (TABLE_SCHEMA = N'EDTE' AND TABLE_NAME = N'CREDITOFISCAL_DET'
       AND COLUMN_NAME IN (N'ID_SOLICITUD', N'ID_SOLIC_AGRI_PROD', N'UID_SOLIC_AGRI_PROD'))
ORDER BY TABLE_NAME, COLUMN_NAME;
GO
