USE [PH2];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'[EPROVEEDOR].[COMPRA_EXTERIOR]', N'U') IS NULL
        THROW 50000, N'No existe la tabla EPROVEEDOR.COMPRA_EXTERIOR.', 1;

    IF OBJECT_ID(N'[ECOMPRAS].[TIPO_IMPORTACION]', N'U') IS NULL
        THROW 50001, N'No existe el catálogo ECOMPRAS.TIPO_IMPORTACION.', 1;

    IF COL_LENGTH(N'[EPROVEEDOR].[COMPRA_EXTERIOR]', N'ID_TIPO_IMPORTACION') IS NULL
    BEGIN
        ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]
            ADD [ID_TIPO_IMPORTACION] INT NULL;
    END;

    IF NOT EXISTS
    (
        SELECT 1
        FROM sys.foreign_keys
        WHERE parent_object_id = OBJECT_ID(N'[EPROVEEDOR].[COMPRA_EXTERIOR]')
          AND name = N'FK_COMPRA_EXTERIOR_TIPO_IMPORTACION'
    )
    BEGIN
        ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] WITH CHECK
            ADD CONSTRAINT [FK_COMPRA_EXTERIOR_TIPO_IMPORTACION]
            FOREIGN KEY ([ID_TIPO_IMPORTACION])
            REFERENCES [ECOMPRAS].[TIPO_IMPORTACION] ([ID_TIPO_IMPORTACION]);

        ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]
            CHECK CONSTRAINT [FK_COMPRA_EXTERIOR_TIPO_IMPORTACION];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO

SELECT
    C.name AS COLUMNA,
    FK.name AS LLAVE_FORANEA,
    OBJECT_SCHEMA_NAME(FK.referenced_object_id) AS ESQUEMA_REFERENCIADO,
    OBJECT_NAME(FK.referenced_object_id) AS TABLA_REFERENCIADA
FROM sys.columns AS C
LEFT JOIN sys.foreign_key_columns AS FKC
    ON FKC.parent_object_id = C.object_id
   AND FKC.parent_column_id = C.column_id
LEFT JOIN sys.foreign_keys AS FK
    ON FK.object_id = FKC.constraint_object_id
WHERE C.object_id = OBJECT_ID(N'[EPROVEEDOR].[COMPRA_EXTERIOR]')
  AND C.name = N'ID_TIPO_IMPORTACION';
GO
