USE [PH2]
GO

-- Para una instalación nueva. Si la tabla ya existe en dbo, use la migración
-- Database/Migrations/20260823_Renombrar_CREDITO_FISCAL_COMPRA_a_COMPRA_EXTERIOR.sql.
IF SCHEMA_ID(N'EPROVEEDOR') IS NULL
BEGIN
    EXEC(N'CREATE SCHEMA [EPROVEEDOR] AUTHORIZATION [dbo];');
END;
GO

IF OBJECT_ID(N'[dbo].[CREDITO_FISCAL_COMPRA]', N'U') IS NOT NULL
BEGIN
    THROW 50000, N'La tabla ya existe en dbo. Ejecute el script de migración para conservar sus datos y relaciones.', 1;
END;
GO

IF OBJECT_ID(N'[EPROVEEDOR].[CREDITO_FISCAL_COMPRA]', N'U') IS NOT NULL
BEGIN
    THROW 50001, N'La tabla anterior existe en EPROVEEDOR. Ejecute la migración de renombrado.', 1;
END;
GO

IF OBJECT_ID(N'[EPROVEEDOR].[COMPRA_EXTERIOR]', N'U') IS NOT NULL
BEGIN
    THROW 50002, N'La tabla [EPROVEEDOR].[COMPRA_EXTERIOR] ya existe.', 1;
END;
GO

/****** Object:  Table [EPROVEEDOR].[COMPRA_EXTERIOR]    Script Date: 23/8/2026 01:00:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [EPROVEEDOR].[COMPRA_EXTERIOR](
	[ID_COMPRA_EXTERIOR] [int] NOT NULL,
	[ID_QUEDAN] [int] NULL,
	[NUM_QUEDAN] [int] NULL,
	[ID_CHEQUE] [int] NULL,
	[NUM_CHEQUE] [int] NULL,
	[ID_TIPO_DTE] [int] NULL,
	[NUM_CONTROL] [nvarchar](60) NULL,
	[COD_GENERACION] [nvarchar](60) NULL,
	[SELLO_RECIBIDO] [nvarchar](60) NULL,
	[FECHA_EMISION] [datetime] NULL,
	[TIPO_MONEDA] [nvarchar](3) NULL,
	[ID_ENTIDAD] [int] NULL,
	[CODIGO_ENTIDAD] [nvarchar](20) NULL,
	[FECHA_RECIBIDO] [datetime] NULL,
	[FECHA_VENCE] [datetime] NULL,
	[ORDEN] [nvarchar](50) NULL,
	[ID_SUCURSAL] [int] NULL,
	[ID_TIPO_SERVI] [int] NULL,
	[ID_TIPO_IMPORTACION] [int] NULL,
	[ID_TIPO_OPERA] [int] NULL,
	[ID_CLASIFICA] [int] NULL,
	[ID_SECTOR] [int] NULL,
	[ID_TIPO_COSTO] [int] NULL,
	[ID_TIPO_RENTA] [int] NULL,
	[NO_SUJETA] [numeric](20, 2) NULL,
	[EXENTA] [numeric](20, 2) NULL,
	[GRAVADA] [numeric](20, 2) NULL,
	[IVA] [numeric](20, 2) NULL,
	[FOVIAL] [numeric](20, 2) NULL,
	[COTRANS] [numeric](20, 2) NULL,
	[TOTAL] [numeric](20, 2) NULL,
	[CARGO] [numeric](20, 2) NULL,
	[ABONO] [numeric](20, 2) NULL,
	[APLICABLE_RENTA] [numeric](20, 2) NULL,
	[RENTA] [numeric](20, 2) NULL,
	[IVAR] [numeric](20, 2) NULL,
	[SALDO] [numeric](20, 2) NULL,
	[ID_COMPROBANTE_RET] [int] NULL,
	[ID_CCF_COMPRA_ASOCIADO] [int] NULL,
	[OBSERVACION] [nvarchar](1000) NULL,
	[USUARIO_CREA] [nvarchar](100) NULL,
	[FECHA_CREA] [datetime] NULL,
	[USUARIO_ACT] [nvarchar](100) NULL,
	[FECHA_ACT] [datetime] NULL,
	[UID_ENLACE_CHEQUE] [nvarchar](60) NULL,
	[SALFEC] [char](6) NULL,
	[UID_DOCUMENTO] [char](36) NULL,
 CONSTRAINT [PK_COMPRA_EXTERIOR] PRIMARY KEY CLUSTERED 
(
	[ID_COMPRA_EXTERIOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR01] FOREIGN KEY([ID_QUEDAN])
REFERENCES [dbo].[QUEDAN] ([ID_QUEDAN])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR01]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR02] FOREIGN KEY([ID_CHEQUE])
REFERENCES [dbo].[CHEQUE] ([ID_CHEQUE])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR02]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR03] FOREIGN KEY([ID_ENTIDAD])
REFERENCES [dbo].[ENTIDAD] ([ID_ENTIDAD])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR03]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR04] FOREIGN KEY([ID_TIPO_DTE])
REFERENCES [dbo].[TIPO_DTE] ([ID_TIPO_DTE])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR04]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR05] FOREIGN KEY([ID_SUCURSAL])
REFERENCES [dbo].[SUCURSAL] ([ID_SUCURSAL])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR05]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR06] FOREIGN KEY([ID_TIPO_SERVI])
REFERENCES [dbo].[COMPRA_TIPO_SERVICIO] ([ID_TIPO_SERVI])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR06]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR_TIPO_IMPORTACION] FOREIGN KEY([ID_TIPO_IMPORTACION])
REFERENCES [ECOMPRAS].[TIPO_IMPORTACION] ([ID_TIPO_IMPORTACION])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR_TIPO_IMPORTACION]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR07] FOREIGN KEY([ID_TIPO_OPERA])
REFERENCES [dbo].[COMPRA_TIPO_OPERACION] ([ID_TIPO_OPERA])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR07]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR08] FOREIGN KEY([ID_CLASIFICA])
REFERENCES [dbo].[COMPRA_CLASIFICACION] ([ID_CLASIFICA])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR08]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR09] FOREIGN KEY([ID_SECTOR])
REFERENCES [dbo].[COMPRA_SECTOR] ([ID_SECTOR])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR09]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR11] FOREIGN KEY([ID_TIPO_RENTA])
REFERENCES [dbo].[TIPO_RENTA] ([ID_TIPO_RENTA])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR11]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR10] FOREIGN KEY([ID_TIPO_COSTO])
REFERENCES [dbo].[COMPRA_TIPO_COSTO] ([ID_TIPO_COSTO])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR10]
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXTERIOR12] FOREIGN KEY([ID_COMPROBANTE_RET])
REFERENCES [dbo].[COMPROBANTE_RETENCION] ([ID_COMPROBANTE_RET])
GO

ALTER TABLE [EPROVEEDOR].[COMPRA_EXTERIOR] CHECK CONSTRAINT [FK_COMPRA_EXTERIOR12]
GO

EXEC(N'
CREATE OR ALTER VIEW [dbo].[CREDITO_FISCAL_COMPRA]
AS
    SELECT
        [ID_COMPRA_EXTERIOR] AS [ID_CCF_COMPRA],
        [ID_QUEDAN], [NUM_QUEDAN], [ID_CHEQUE], [NUM_CHEQUE],
        [ID_TIPO_DTE], [NUM_CONTROL], [COD_GENERACION], [SELLO_RECIBIDO],
        [FECHA_EMISION], [TIPO_MONEDA], [ID_ENTIDAD], [CODIGO_ENTIDAD],
        [FECHA_RECIBIDO], [FECHA_VENCE], [ORDEN], [ID_SUCURSAL],
        [ID_TIPO_SERVI], [ID_TIPO_OPERA], [ID_CLASIFICA], [ID_SECTOR],
        [ID_TIPO_COSTO], [ID_TIPO_RENTA], [NO_SUJETA], [EXENTA], [GRAVADA],
        [IVA], [FOVIAL], [COTRANS], [TOTAL], [CARGO], [ABONO],
        [APLICABLE_RENTA], [RENTA], [IVAR], [SALDO], [ID_COMPROBANTE_RET],
        [ID_CCF_COMPRA_ASOCIADO], [OBSERVACION], [USUARIO_CREA], [FECHA_CREA],
        [USUARIO_ACT], [FECHA_ACT], [UID_ENLACE_CHEQUE], [SALFEC], [UID_DOCUMENTO]
    FROM [EPROVEEDOR].[COMPRA_EXTERIOR];
');
GO
